export const ACTION_TYPES = {
  LOGIN: 'LOGIN',
  CREATE_SESSION: 'CREATE_SESSION',
  SET_ERROR: 'SET_ERROR',
  SET_NOTICE: 'SET_NOTICE',
  SET_ALERT: 'SET_ALERT',
  CREATE_SESSION_ERROR: 'CREATE_SESSION_ERROR'
}



