export const SEARCH_JOB = '/search-job'
export const POST_JOB = '/post'
export const PENDING_JOB = '/jobs/pending'
export const PENDING_JOB_DETAILS = '/jobs/pending_job_details'
export const INVITED_JOBS = '/jobs/:id/invited-jobs'
