export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_SUCCESS_USER = 'CREATE_SUCCESS_USER';
export const CREATE_ERROR_USER = 'CREATE_ERROR_USER';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const SET_ERROR = 'SET_ERROR';
export const SET_NOTICE = 'SET_NOTICE';
export const SET_ALERT = 'SET_ALERT';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const PENDING_JOB = 'PENDING_JOB';
export const PENDING_JOB_SUCCESS = 'PENDING_JOB_SUCCESS';
export const PENDING_JOB_ERROR = 'PENDING_JOB_ERROR';
export const PENDING_JOB_RESET = 'PENDING_JOB_RESET';

export const PENDING_JOB_DETAILS = 'PENDING_JOB_DETAILS';
export const PENDING_JOB_DETAILS_SUCCESS = 'PENDING_JOB_DETAILS_SUCCESS';
export const PENDING_JOB_DETAILS_RESET = 'PENDING_JOB_DETAILS_RESET';
export const PENDING_JOB_DETAILS_ERROR = 'PENDING_JOB_DETAILS_ERROR';

export const CREATE_JOB = 'CREATE_JOB';
export const SUCCESS_CREATE_JOB = 'SUCCESS_CREATE_JOB';
export const ERROR_CREATE_JOB = 'ERROR_CREATE_JOB';

export const PENDING_JOB_DELETE = 'PENDING_JOB_DELETE';
export const PENDING_JOB_DELETE_SUCCESS = 'PENDING_JOB_DELETE_SUCCESS';
export const PENDING_JOB_DELETE_ERROR = 'PENDING_JOB_DELETE_ERROR';

export const INVITED_JOBS = 'INVITED_JOBS';
export const INVITED_JOBS_SUCCESS = 'INVITED_JOBS_SUCCESS';
export const INVITED_JOBS_ERROR = 'INVITED_JOBS_ERROR';
export const INVITED_JOBS_RESET = 'INVITED_JOBS_RESET';

export const INVITED_JOBS_USER_DETAILS = 'INVITED_JOBS_USER_DETAILS';
export const INVITED_JOBS_USER_DETAILS_SUCCESS = 'INVITED_JOBS_USER_DETAILS_SUCCESS';
export const INVITED_JOBS_USER_DETAILS_ERROR = 'INVITED_JOBS_USER_DETAILS_ERROR';
export const INVITED_JOBS_USER_DETAILS_RESET = 'INVITED_JOBS_USER_DETAILS_RESET';
export const INVITED_JOBS_USER_UPDATE_LIKE = 'INVITED_JOBS_USER_UPDATE_LIKE';

// export const LIKE_UNLIKE_USER = 'LIKE_UNLIKE_USER' 
// export const LIKE_UNLIKE_USER_SUCCESS = 'LIKE_UNLIKE_USER_SUCCESS' 
// export const LIKE_UNLIKE_USER_ERROR = 'LIKE_UNLIKE_USER_ERROR' 

export const REHYDRATED_DONE = 'REHYDRATED_DONE';

export const CHANGE_TAB_NAV = 'CHANGE_TAB_NAV';

export const RESET_AUTH_ERROR = 'RESET_AUTH_ERROR'



